# stub from https://github.com/softprops/action-gh-release 
name: Release 
on:
  push:
    tags:
      - "*.*.*"
  # pull_request:
  #   branches: main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build Linux glibc image
        run: |
          VERSION=$(git describe --tags --always --dirty 2>/dev/null || echo "2.1.5")
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
          docker build --build-arg VERSION="$VERSION" .

      - name: Build Linux musl image
        run: |
          docker build -f Dockerfile.musl --build-arg VERSION="$VERSION" .

      - name: Compile executable on Linux glibc
        run: |
          mkdir -p build
          VERSION=$(git describe --tags --always --dirty 2>/dev/null || echo "2.1.2")
          docker run \
            -e VERSION="$VERSION" \
            -v ./build:/root/scheme-langserver/build/ \
            $(docker build -q --build-arg VERSION="$VERSION" .) \
            bash -c 'source .akku/bin/activate
                     compile-chez-program run.ss --static
                     test -f run || { echo "compile-chez-program failed: run not found"; exit 1; }
                     mv run "build/scheme-langserver-x86_64-linux-glibc" || exit 1
                     '

      - name: Compile executable on Linux musl
        run: |
          mkdir -p build
          docker run \
            -e VERSION="$VERSION" \
            -v ./build:/root/scheme-langserver/build/ \
            $(docker build -f Dockerfile.musl -q --build-arg VERSION="$VERSION" .) \
            ash -c 'source .akku/bin/activate
                    compile-chez-program run.ss --static
                    test -f run || { echo "compile-chez-program failed: run not found"; exit 1; }
                    mv run "build/scheme-langserver-x86_64-linux-musl" || exit 1
                    '

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          repo: ufo5260987423/scheme-langserver
          files: |
            build/scheme-langserver-x86_64-linux-glibc
            build/scheme-langserver-x86_64-linux-musl
